### ISSUE TITLE
Keypoint Annotation: Group ID inheritance broken for numeric shortcuts & across images

### ISSUE THREAD

**Issue by MMagicLoren** [CVHub520/X-AnyLabeling#1149]
### Search before asking

- [x] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

I am very pleased to see your update, which added the use of the previous "group_i" function. This feature is very practical, and I immediately updated it. However, when using it, I found that the numeric shortcut keys did not inherit the "group_id" of the first step of annotating the object detection box. I hope this bug can be fixed as soon as possible, because numeric shortcut keys are too friendly to keypoint annotation and can greatly improve work efficiency.

### Information

Application Information:
    {'App name': 'X-AnyLabeling', 'App version': '3.2.5', 'Device': 'GPU'}

System Information:
    {'CPU': 'Intel64 Family 6 Model 183 Stepping 1, GenuineIntel',
     'CUDA': None,
     'GPU': '0, NVIDIA GeForce RTX 3050 OEM, 8192',
     'Operating System': 'Windows-10-10.0.19045-SP0',
     'Python Version': '3.10.18'}

Package Information:
    {'ONNX Runtime GPU Version': '1.23.0',
     'ONNX Runtime Version': '1.23.0',
     'ONNX Version': '1.19.0',
     'OpenCV Contrib Python Headless Version': '4.11.0.86',
     'PyQt5 Version': '5.15.7'}

### Link to a Reproducible Demonstration Video

无

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MMagicLoren** [comment]
And it can only inherit 'group_id' when annotating one image, and cannot be inherited when switching to the next image.

**Comment by CVHub520** [comment]
Hey there! @MMagicLoren, thanks so much for your detailed report and for the kind words about the `group_i` feature! We really appreciate your feedback. 🤗

You've accurately highlighted two important issues: the numeric shortcut keys for keypoint annotation currently don't inherit the `group_id` from the object detection box, and this inheritance doesn't persist when switching to the next image. This definitely impacts efficiency, as you pointed out.

We'll prioritize this fix to ensure that the `auto_use_last_gid` functionality properly applies to digit shortcuts for keypoint annotation, and that the `group_id` is correctly reset when you move to a new image. Your insights are invaluable for improving X-AnyLabeling! ✨

**Comment by MMagicLoren** [comment]
Thank you very much for your contribution. I encountered the following issue during use:
When labeling keypoints, using the numeric shortcut keys is very convenient. However, executing Ctrl+Z to undo an action also reverses the “Group ID” of the previous label. I hope the developer can fix this bug.
Version：
X-AnyLabeling v3.3.0-beta launched!

**Comment by CVHub520** [comment]
Hi @MMagicLoren,

Thank you so much for following up and reporting this! You've uncovered a very subtle bug where `Ctrl+Z` was unexpectedly reversing the Group ID along with the action, especially when using numeric shortcut keys for keypoints. We really appreciate you catching these intricate details! 🙏

We're pleased to let you know that we've already addressed and fixed this issue. Please feel free to update X-AnyLabeling to the latest commit when it becomes available, and let us know if everything is now working smoothly for you. Your continued feedback is incredibly valuable!

**Comment by MMagicLoren** [comment]
Thank you for your contribution, but I've still encountered an issue: when switching images during the keypoint annotation task, the “Group_id” fails to carry over. You previously fixed this problem, but it has now reappeared.

**Comment by CVHub520** [comment]
> Thank you for your contribution, but I've still encountered an issue: when switching images during the keypoint annotation task, the “Group_id” fails to carry over. You previously fixed this problem, but it has now reappeared.

Thank you for the detailed feedback and patience throughout this process! 

I've implemented a comprehensive fix that addresses the Group ID persistence issue across multiple scenarios. The root cause was more complex than initially apparent ~ :( it involved the interplay between the undo/backup system, label update mechanism, and state preservation logic.

Some key improvements made:
- Modified the shape backup mechanism to capture Group ID before creating snapshots
- Updated the undo operation to preserve the last-used Group ID state  
- Synchronized Group ID updates when editing existing shapes
- Ensured proper state propagation when switching between images

This bug was particularly challenging because it touched several interconnected components - fixing one aspect would sometimes expose edge cases in another (backup vs. undo vs. image switching vs. auto-labeling). Each scenario required careful balancing to avoid breaking existing functionality.

The current implementation should now handle:
- Group ID persistence when using digit shortcuts
- Group ID preservation across image switches
- Correct undo behavior without affecting Group ID state
- Proper Group ID inheritance when editing shapes with auto_use_last_label enabled

I'd greatly appreciate your thorough testing across different workflows, especially edge cases like rapid undo/redo operations and mixed annotation modes. Please report any remaining issues you encounter.

Thanks for helping improve X-AnyLabeling!
